### PR TITLE
Changed shortcut system to use Chromes command API

### PR DESCRIPTION
**Pull request by koglerch13**
- configured a default shortcut in manifest.json
- adapted background.js and tab-switcher.js, so the switcher is now triggered from background.js (using the chrome command)
- removed keymaster.js, since it is no longer needed

### CODE REVIEW

**Comment by koglerch13** [comment]
Adressing the concerns in https://github.com/kamranahmedse/tab-switcher/issues/3 :
Ctrl+Shift+K is set as a default. The user does not need to manually set the shortcut (but can, if he wants to)

**Comment by capaj** [comment]
@kamranahmedse this seems like much better solution for the hotkey. Please please merge this!

**Comment by capaj** [comment]
@kamranahmedse is there a problem with this PR aside from the git conflict? Help us identify it and resolve it. Why won't you merge this?

**Comment by kamranahmedse** [comment]
Sorry for the late reply guys.

It didn't work for me on my Mac unless I setup the shortcut manually. 
Plus I have been working on the options page which relies on the keymaster and would allow the user to change this shortcut from the extension options itself so I was refraining to merge this.

@koglerch13 thanks though.

**Comment by capaj** [comment]
@kamranahmedse so instead of using official chrome solution for this, you opt rather for halfworking hack. Well, that's a pity. @koglerch13 maybe it would be better to publish our own version of the extension to the chrome store with a proper hot-key support? Do you want to do this or shall I?

**Comment by koglerch13** [comment]
@kamranahmedse I would still strongly suggest you to implement the Chrome-way of handling shortcuts. Your solution with keymaster is guaranteed to produce conflicts with some applications and extensions.

@capaj I would really prefer the chrome api to be used in this project, instead creating another, but if it will not happen, I would be open to publish a fork using the proper way of handling hotkeys. 
Maybe we can convince @kamranahmedse to implemement it. 

Can someone with a Mac perhaps verify, that default shortcuts do not work?

**Comment by capaj** [comment]
@koglerch13 my friend has a mac, I will send him a tar of your fork and let him try it next week.

**Comment by koglerch13** [comment]
@capaj That would be great, thanks. I guess that the application needs to be (re-)installed for the hotkey suggestion to apply. If that works properly, there should be no reason not to publish it that way (either here or in a fork)

**Comment by pedrocatre** [comment]
Hey @koglerch13  I'm using part of this project for something else I'm building and I was wondering, does using the Chrome API help resolve command conflicts with other shortcuts and extensions? If so can you tell me how?

**Comment by koglerch13** [comment]
@pedrocatre As far as i know it does not really resolve them. I have read somewhere that a default shortcut is simply not applied if it is already in use by another extension.

**Comment by pedrocatre** [comment]
@koglerch13 ok that is what I assumed reading the documentation. Thanks.

**Comment by wachunei** [comment]
@koglerch13 I'm on a mac and it works by default.

**Comment by koglerch13** [comment]
@wachunei Thats awesome! Thanks for checking!
@kamranahmedse would you maybe consider implementing Chrome-Shortcuts now?

**Comment by pedrocatre** [comment]
I do not see a very compelling reason to change this (although it seems like a "should have") since supposedly there is going to be an options page where you can change the shortcut. That being said I tried it on my mac and it did work for me without having to specify the shortcut, so there does not seem to be a very compelling reason not to have it either.

**Comment by pedrocatre** [comment]
@kamranahmedse fyi I was just working on another chrome extension and noticed that if I set the command to Command+Shift+O or Command+Shift+L it would not set it by default, I had to manually set the shortcut. I think chrome is detecting a possible conflict and that is why it does not accept it, however I did not see any conflict. One possibility is that chrome just detects the conflict for Command+O and Command+L (which do trigger actions). If I set Command+Shift+B it works and Command+B has no action associated with it so maybe that is why.

I'm not 100% sure on the reason for the behaviour, just thought I would share some findings.

**Comment by nilbuild** [comment]
@pedrocatre thank you for sharing. Actually I faced the same and that is why I don't want to rely on the shortcuts and use the _keymaster_ that will allow more control.

**Comment by capaj** [comment]
@kamranahmedse you are aware that the shortcut only works when user has focus inside a page? When I click in my url bar, and hit ctrl+shift+k nothing happens. This is basic workflow, which should just work.

**Pull request closed without merging**
